[package]
name = "electric-meter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uart-linux = { git = "https://github.com/whqee/uart_linux", version = "0.1.0" }
